version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443" # Map HTTPS port
    volumes:
      - ./fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - ./privkey.pem:/etc/ssl/private/privkey.pem:ro
      - ./static:/app/static
